[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
OLLAMA_HOST = "0.0.0.0"
OLLAMA_PORT = "11434"
