#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged
npx lint-staged

# Run tests if available
if [ -f "package.json" ] && grep -q '"test"' package.json; then
  npm test -- --bail --findRelatedTests
fi
